/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsShareTokenRouteImport } from './routes/reports.share.$token'
import { Route as ApiPublicReportRouteImport } from './routes/api/public/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsShareTokenRoute = ReportsShareTokenRouteImport.update({
  id: '/reports/share/$token',
  path: '/reports/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReportRoute = ApiPublicReportRouteImport.update({
  id: '/api/public/report',
  path: '/api/public/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/report': typeof ApiPublicReportRoute
  '/reports/share/$token': typeof ReportsShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/report': typeof ApiPublicReportRoute
  '/reports/share/$token': typeof ReportsShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/report': typeof ApiPublicReportRoute
  '/reports/share/$token': typeof ReportsShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/report' | '/reports/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/report' | '/reports/share/$token'
  id: '__root__' | '/' | '/api/public/report' | '/reports/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicReportRoute: typeof ApiPublicReportRoute
  ReportsShareTokenRoute: typeof ReportsShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/share/$token': {
      id: '/reports/share/$token'
      path: '/reports/share/$token'
      fullPath: '/reports/share/$token'
      preLoaderRoute: typeof ReportsShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/report': {
      id: '/api/public/report'
      path: '/api/public/report'
      fullPath: '/api/public/report'
      preLoaderRoute: typeof ApiPublicReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicReportRoute: ApiPublicReportRoute,
  ReportsShareTokenRoute: ReportsShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
